# Generated by Django 4.2.3 on 2023-07-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"], "verbose_name_plural": "Dishes"},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"], "verbose_name_plural": "Dish Types"},
        ),
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
